#!/usr/bin/env node
// Deterministic validation for black-box case files generated by loctek-test-case.
// Replaces "AI self-check" gates with hard checks:
//   1. REQ Baseline table exists
//   2. Overview table <-> detail sections are 1:1 (bidirectional diff, no orphans)
//   3. Every REQ-ID referenced by a TC exists in the baseline
//   4. REQ forward coverage >= threshold (default 95)
//   5. 6-type commitment table: promised min counts vs actual counts (warn by default)
//
// Usage:
//   node validate-cases.mjs <case-file.md> [--min 95] [--strict] [--json]

import { readFileSync } from "node:fs";

function parseArgs(argv) {
  const out = { file: "", min: 95, strict: false, json: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--min") out.min = Number(argv[++i]);
    else if (a === "--strict") out.strict = true;
    else if (a === "--json") out.json = true;
    else if (!a.startsWith("--")) out.file = a;
  }
  return out;
}

const REQ_RE = /\bREQ-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*-\d+\b/g;
const TC_RE = /\bTC-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*-\d+\b/g;
const TYPE_NAMES = ["功能测试", "安全测试", "性能测试", "可靠性测试", "兼容性测试", "易用性测试"];

function uniq(list) {
  return [...new Set(list.map((s) => s.toUpperCase()))];
}

const args = parseArgs(process.argv.slice(2));
if (!args.file) {
  console.error("用法: node validate-cases.mjs <用例文件.md> [--min 95] [--strict] [--json]");
  process.exit(2);
}

let text;
try {
  text = readFileSync(args.file, "utf8");
} catch (err) {
  console.error(`无法读取文件: ${err.message}`);
  process.exit(2);
}
const lines = text.split("\n");

const failures = [];
const warnings = [];

// --- 1. REQ baseline table ---
const hasBaselineTable = lines.some((l) => l.includes("REQ-ID") && l.trim().startsWith("|"));
// REQ-IDs that appear in the baseline section = REQ-IDs mentioned before the overview table starts.
// Simpler robust approach: a REQ counts as "in baseline" if it appears on a table row that is not
// an overview row (overview rows are identified by starting with a TC id).
const overviewRowRe = /^\|\s*TC-[^|]*\|/;
const baselineReqsOnRows = uniq(
  lines.filter((l) => l.trim().startsWith("|") && !overviewRowRe.test(l)).join("\n").match(REQ_RE) || []
);
if (!hasBaselineTable) failures.push("缺少 REQ Baseline 基线表（表头需包含 REQ-ID 列）");

// --- 2. Overview <-> detail 1:1 ---
const detailHeadings = lines.filter((l) => /^#{3,6}\s+TC-/.test(l));
const detailTcs = uniq(detailHeadings.join("\n").match(TC_RE) || []);
const overviewTcs = uniq(lines.filter((l) => overviewRowRe.test(l)).join("\n").match(TC_RE) || []);
const overviewOnly = overviewTcs.filter((id) => !detailTcs.includes(id));
const detailOnly = detailTcs.filter((id) => !overviewTcs.includes(id));
if (overviewTcs.length === 0) failures.push("未找到测试概览表（应存在以 | TC- 开头的行）");
if (detailTcs.length === 0) failures.push("未找到详述用例（应存在 '### TC-' 三级标题）");
overviewOnly.forEach((id) => failures.push(`概览表有但详述缺失: ${id}`));
detailOnly.forEach((id) => failures.push(`详述有但概览表缺失: ${id}`));

// --- 3. REQ-ID validity ---
const overviewReqs = uniq(
  lines.filter((l) => overviewRowRe.test(l)).join("\n").match(REQ_RE) || []
);
const detailReqs = uniq(detailHeadings.join("\n").match(REQ_RE) || []);
const unknownReqs = uniq([...overviewReqs, ...detailReqs]).filter((r) => !baselineReqsOnRows.includes(r));
unknownReqs.forEach((r) => failures.push(`TC 引用了基线中不存在的 REQ-ID: ${r}`));

// --- 4. REQ forward coverage ---
const coveredReqs = uniq([...overviewReqs, ...detailReqs]).filter((r) => baselineReqsOnRows.includes(r));
const uncovered = baselineReqsOnRows.filter((r) => !coveredReqs.includes(r));
const coverage = baselineReqsOnRows.length ? (coveredReqs.length / baselineReqsOnRows.length) * 100 : 0;
if (baselineReqsOnRows.length === 0) {
  failures.push("REQ 基线表中没有可识别的 REQ-ID（格式应为 REQ-XXX-001）");
} else if (coverage < args.min) {
  failures.push(`需求正向覆盖率 ${coverage.toFixed(1)}% 低于红线 ${args.min}%；未覆盖: ${uncovered.join(", ")}`);
}

// --- 5. Commitment table vs actual counts ---
const commitmentRows = lines
  .map((l) => l.match(/^\|\s*\d+\s*\|\s*(功能测试|安全测试|性能测试|可靠性测试|兼容性测试|易用性测试)\s*\|(.+)\|\s*$/))
  .filter(Boolean);
const hasCommitmentTable = commitmentRows.length > 0;
if (!hasCommitmentTable) warnings.push("未找到测试类型覆盖承诺表（6 类强制评估）");

const allText = text;
for (const row of commitmentRows) {
  const typeName = row[1];
  const rest = row[2];
  const covered = /^\s*✅/.test(rest);
  const minMatch = rest.match(/≥\s*(\d+)/);
  if (!covered) continue;
  const promised = minMatch ? Number(minMatch[1]) : 0;
  const cellsOf = (l) => l.split("|").map((c) => c.trim());
  const actualOverview = lines.filter((l) => overviewRowRe.test(l) && cellsOf(l).some((c) => c === typeName)).length;
  const actualTags = (allText.match(new RegExp(`🏷️[^\\n]*${typeName}`, "g")) || []).length;
  const actual = Math.max(actualOverview, actualTags);
  if (promised > 0 && actual < promised) {
    const msg = `${typeName}: 承诺 ≥ ${promised} 条，实际约 ${actual} 条（概览类型列 ${actualOverview} / 标签 ${actualTags}）`;
    if (args.strict) failures.push(`测试类型未达标 — ${msg}`);
    else warnings.push(`测试类型疑似未达标 — ${msg}（请人工核对类型列写法）`);
  }
}

// --- quality hints ---
const missingTraceback = detailHeadings.length - (text.match(/\*\*需求追溯\*\*/g) || []).length;
if (missingTraceback > 0) warnings.push(`${missingTraceback} 条详述用例可能缺少「需求追溯」字段`);
if (!/双线|UI|DB|📡|💻/.test(text)) warnings.push("未检测到双线预期结果（UI 与 DB/下游）的迹象");

const result = {
  file: args.file,
  baselineReqs: baselineReqsOnRows.length,
  overviewTcs: overviewTcs.length,
  detailTcs: detailTcs.length,
  coverage: Number(coverage.toFixed(1)),
  uncovered,
  failures,
  warnings,
};

if (args.json) {
  console.log(JSON.stringify(result, null, 2));
} else {
  console.log(`用例校验: ${args.file}`);
  console.log(`  REQ 基线条目: ${result.baselineReqs}`);
  console.log(`  概览用例: ${result.overviewTcs} / 详述用例: ${result.detailTcs}`);
  console.log(`  REQ 正向覆盖率: ${result.coverage}%（红线 ${args.min}%）`);
  if (warnings.length) {
    console.log("警告:");
    warnings.forEach((w) => console.log(`  ⚠️  ${w}`));
  }
  if (failures.length) {
    console.log("未通过:");
    failures.forEach((f) => console.log(`  ❌ ${f}`));
    process.exit(1);
  }
  console.log("✅ 校验通过");
}
process.exit(failures.length ? 1 : 0);
